---
title: "Publications & Presentations"
---

# Publications

Recent articles and papers related to mobile and wearable data science co-authored by interest group members: 

+ [Comparing Step Counting Algorithms for High-Resolution Wrist Accelerometry Data in NHANES 2011-2014](https://pubmed.ncbi.nlm.nih.gov/39589008/) (2025) by Koffman et. al.
+ [A Flexible Framework for Synthesizing Categorical Sequences with Application to Human Activity Patterns](https://www.tandfonline.com/doi/full/10.1080/10618600.2025.2450461) (2025) by Huang et al.
+ [Adjacency Matrix Decomposition Clustering for Human Activity Data](https://www.tandfonline.com/doi/abs/10.1080/01621459.2025.2506196) (2025) by Barnard et al.

Let us know if you have a publication you would like to be featured! 

# Presentations

## JSM 2025

JSM 2025 in Nashville will features several sessions that may be of interest to MWDS members:

*Sunday, August 3, 2025*

- 2:00 PM - 3:50 PM	Functional Data Analysis in The Era of Digital Health (Invited Paper Session)
- 2:00 PM - 3:50 PM	Innovating Drug Development through Advanced Statistical and AI Methods for Digital Wearable Sensor Data	(Topic-Contributed Paper)

*Monday, August 4, 2025*

- 8:30 AM - 10:20 AM	AI for AD/ADRD Care: Essentials to Improve Learning Health Systems’ Management of Aging People (Invited Paper Session)
- 8:30 AM - 10:20 AM	Big Data Analysis with Applications to Biostatistics (Topic-Contributed Paper)
- 10:30 AM - 12:20 PM	Advancements in Utilizing Mobile Health Data for Mental Health Research (Invited Paper Session)

*Tuesday, August 5, 2025*

- 10:30 AM - 12:20 PM	Contributed Poster Presentations: Section on Statistical Computing (Contributed Posters)
- 1:00 PM - 1:50 PM		Mobile & Wearable Data Science Interest Group Business Meeting (ASA Meetings and Events)


```{=html}
<a href="mailto:wearableds@gmail.com" class="contact-button">📩 Contact Us</a>

<style>
  .contact-button {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    color: #fff;
    background-color: #007bff;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
  }
  
  .contact-button:hover {
    background-color: #0056b3;
  }
</style>
